version: '3'

services:
  db:
    image: postgres:11.4-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: movie_api:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
